project:
  type: website
  output-dir: _site

website:
  title: "Kai Lynn Wong"
  site-url: "https://lynnotto.github.io/potstickers-"
  description: "CV and Research Blog"

  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/Lynnotto/potstickers-
      - icon: envelope
        href: mailto:wongkailynn@gmail.com

  page-footer:
    center: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
